---
title: "2016 US-California Marriage Tax Penalty/Bonus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: default
runtime: shiny
---

```{r global, include=FALSE}

library(plotly)
library(shiny)

library(htmltools)
if (file.exists('google-analytics.js')){
  attachDependencies(tagList(),
      htmlDependency("google-analytics", version = "1.1.1",
                     ".", script = "google-analytics.js", 
                     all_files = FALSE)
  )
}
source(file = 'tax_engine.R')

marriage.cost = read_feather('marriage-cost.feather')
f.status = list('Married' = 'Married', 
                'Single' = 'Single', 
                'Head of Household' = 'hoh')
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

radioButtons('married', 'Filing Status', f.status, selected = 'Married')
sliderInput('my.income', 'Your Income',min = 0, max = 600000, 
            value = 150000, step = 2000)
conditionalPanel(
  condition = "input.married == 'Married'",
  sliderInput('spouse.income', 'Partner Income', min = 0, 
              max = 600000, value = 120000, step = 2000)
)
sliderInput('children', 'Number of Children', min=0, max=3, value=1)


renderText('Your Tax:')
renderUI(tags$h3(prettyNum(round(get.just.tax()),big.mark=",")))


conditionalPanel(
  condition = "input.married == 'Married'",
  renderText('Marriage Tax Penalty:'),
  renderUI(
    h3(
      prettyNum(round(
        marriage.or.divorce(
          kids(),family.income(),inc.ratio()
          )),
        big.mark = ",")
      )
    )
)
renderUI(a('Blog: Understanding Taxes', href = 'https://medium.com/@mrshashi/how-us-taxes-work-afcf265ccb02'))
renderUI(a('Blog: Marriage Penalty', href = 'https://medium.com/@mrshashi/the-american-marriage-tax-penalty-2fb85228c864'))
renderUI(a('Fork me on Github', href = 'https://github.com/mrshashi/taxed'))

```

Column {.tabset}
-----------------------------------------------------------------------

### Bonus or Penalty

```{r}

inc.ratio = reactive({
  if (input$married == 'Married'){
    return(max(input$my.income, input$spouse.income)/(input$my.income + input$spouse.income))
  }
  return(1)
})

family.income = reactive({
  if (input$married == 'Married'){
    return(input$my.income + input$spouse.income)
  }
  return(input$my.income)
})

kids = reactive({
  min(3, input$children)
})

renderPlotly({
  marriage.cost %>%
  filter(children == kids(),
         income.2 < 301000) %>%
  ggplot(aes(income.1, income.2, color = penalty.or.bonus, size = amount))+
  geom_point(alpha=0.4)+
  scale_color_brewer('',palette = 'Set2')+
  scale_size('',range = c(0,6))+
  scale_x_continuous('Your Income', labels = comma)+
  scale_y_continuous('Spouse Income', labels = comma)+
    labs(title = 'Marriage Tax Penalty (or Bonus)')
})

```


### 2016 Taxes

```{r}
data = reactive({
  get.data(input$married, 
           kids(),
           inc.ratio()
           )
})

get.my.tax = reactive({
  my.inc = family.income()
  extract.tax(input$married, kids(), 
              inc.ratio(), my.inc, 
              min.income = my.inc, steps = 1, 
              all = TRUE )
})

get.just.tax = reactive({
  my.inc = family.income()
  extract.tax(input$married, kids(),
              inc.ratio(), my.inc, 
              min.income = my.inc, steps = 1 )
})

renderPlotly({
ggplot(data(), aes(income))+
  geom_line(aes(y = total.tax, color = 'total tax'), alpha=0.4, color = 'red')+
  geom_line(aes(y = carry.home, color = 'carry home'), alpha=0.6, color = '#55CC77')+
  
  scale_color_hue("Where's Money?")+
  scale_y_continuous('Carry Home Income / Tax Paid', labels=comma)+
  scale_x_continuous('Income', labels=comma)
})
```

### Taxes & Credits

```{r}
renderPlotly({
ggplot(data(), aes(income))+
  geom_line(aes(y = social.security, color = 'social security'))+
  geom_line(aes(y = medicare, color = 'medicare'))+
  geom_line(aes(y = state.tax, color = 'state tax'))+
  geom_line(aes(y = federal.tax, color = 'federal tax'))+
  geom_line(aes(y = eic, color = 'earned income credit'))+
  geom_line(aes(y = child.tax.credit, color = 'child tax credit'))+
  geom_line(aes(y = amt.tax, color = 'AMT tax'))+
  scale_color_hue('Where did the taxes go?')+
  scale_y_continuous('Tax',labels=comma)+
  scale_x_continuous('Income', labels=comma)
})
```

### Taxable Income

```{r}
renderPlotly({
ggplot(data(), aes(income))+
  geom_line(aes(y = amt.income, color = 'amt taxable'))+
  geom_line(aes(y = federal.taxable, color = 'federal taxable'))+
  geom_line(aes(y = state.taxable, color = 'state taxable'))+
  scale_color_hue('Where did the taxes go?')+
  scale_y_continuous('Taxable Income',labels=comma)+
  scale_x_continuous('Income',labels=comma)
})
```


### Tax Percentage

```{r}
renderPlotly({
  ggplot(data(), aes(income))+
    geom_line(aes(y = total.tax.percent, color = 'total tax'))+
    geom_line(aes(y = state.percent, color = 'state tax'))+
    geom_line(aes(y = federal.percent, color = 'federal tax'))+
    geom_line(aes(y = amt.percent, color = 'amt tax'))+
    geom_line(aes(y = medicare.percent, color = 'medicare tax'))+
    geom_line(aes(y = social.security.percent, color = 'social security tax'))+
    scale_y_continuous('Total-Tax as % of Income')+
    scale_x_continuous('Income', labels = comma)
})
```

### Federal Exemptions

```{r}
renderPlotly({
ggplot(data(), aes(income))+
  geom_step(aes(y=ded.f.personal, color = 'federal personal exemption'),
            alpha=0.7,
            direction = 'hv')+
  geom_line(aes(y=ded.f.itemized, color = 'final federal exemption'))+
  # geom_line(aes(y=ded.f.itemized.20, color = 'federal exemption 20'))+
  geom_line(aes(y=ded.f.standard, color = 'federal standard exemption'))+
  geom_line(aes(y=state.tax, color = 'state tax'))+
  geom_line(aes(y=amt.exempt, color = 'amt exempt'))+
  scale_color_hue('Exemptions')+
  ggtitle('Exemptions')+
  scale_y_continuous('$',labels=comma)+
  scale_x_continuous('Income',labels=comma)
})
```

### State Exemptions

```{r}
renderPlotly({
ggplot(data(), aes(income))+
  geom_step(aes(y=credit.s.personal, color = 'state personal exemption'))+
  geom_step(aes(y=ded.s.standard, color = 'state standard exemption'))+
  scale_color_hue('Exemption')+
  ggtitle('Exemptions')+
  scale_y_continuous('$',labels=comma)+
  scale_x_continuous('Income',labels=comma)
})
```

### Detailed Tax

```{r}
renderTable(get.my.tax())
```

### Data

```{r}
renderTable(data())
```



